### ISSUE TITLE
Jetson nano error

### ISSUE THREAD

**Issue by neg-dev** [ria-com/nomeroff-net#114]
detectron2                    0.3
tensorflow                    2.3.1+nv20.10
torch                         1.6.0
torchvision                   0.7.0
python3 -c 'import cv2; print(cv2.__version__)'
3.4.6

~/nomeroff-net/examples/py$ python3 demo0.py
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-r3j91qf8 because the default path (/home/sitec/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2020-11-18 19:35:54.165961: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
2020-11-18 19:35:59.322332: W tensorflow/core/platform/profile_utils/cpu_utils.cc:108] Failed to find bogomips or clock in /proc/cpuinfo; cannot determine CPU frequency
2020-11-18 19:35:59.322911: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3017fed0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-18 19:35:59.322974: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-11-18 19:35:59.331767: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-11-18 19:35:59.401921: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-18 19:35:59.402308: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3018fdc0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-11-18 19:35:59.402389: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA Tegra X1, Compute Capability 5.3
2020-11-18 19:35:59.403199: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-18 19:35:59.403354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1742] Found device 0 with properties:
pciBusID: 0000:00:00.0 name: NVIDIA Tegra X1 computeCapability: 5.3
coreClock: 0.9216GHz coreCount: 1 deviceMemorySize: 3.87GiB deviceMemoryBandwidth: 194.55MiB/s
2020-11-18 19:35:59.403672: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
2020-11-18 19:35:59.403901: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2020-11-18 19:35:59.404052: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2020-11-18 19:35:59.404984: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2020-11-18 19:35:59.409850: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2020-11-18 19:35:59.414250: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2020-11-18 19:35:59.415179: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2020-11-18 19:35:59.415778: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-18 19:35:59.416294: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-18 19:35:59.416395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1884] Adding visible gpu devices: 0
2020-11-18 19:35:59.416619: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
2020-11-18 19:36:01.579485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1283] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-18 19:36:01.579582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1289]      0
2020-11-18 19:36:01.579631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1302] 0:   N
2020-11-18 19:36:01.580291: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-18 19:36:01.580777: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-18 19:36:01.580940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1428] Created TensorFlow device (/device:GPU:0 with 147 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
Traceback (most recent call last):
  File "demo0.py", line 17, in <module>
    from NomeroffNet import  Detector
  File "/home/sitec/nomeroff-net/NomeroffNet/__init__.py", line 6, in <module>
    from .DetectronDetector import *
  File "/home/sitec/nomeroff-net/NomeroffNet/DetectronDetector.py", line 9, in <module>
    from detectron2.engine import DefaultPredictor
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/__init__.py", line 11, in <module>
    from .hooks import *
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/hooks.py", line 17, in <module>
    from detectron2.evaluation.testing import flatten_results_dict
  File "/usr/local/lib/python3.6/dist-packages/detectron2/evaluation/__init__.py", line 2, in <module>
    from .cityscapes_evaluation import CityscapesInstanceEvaluator, CityscapesSemSegEvaluator
  File "/usr/local/lib/python3.6/dist-packages/detectron2/evaluation/cityscapes_evaluation.py", line 11, in <module>
    from detectron2.data import MetadataCatalog
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "/usr/local/lib/python3.6/dist-packages/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "/usr/local/lib/python3.6/dist-packages/detectron2/structures/keypoints.py", line 6, in <module>
    from detectron2.layers import interpolate
  File "/usr/local/lib/python3.6/dist-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/usr/local/lib/python3.6/dist-packages/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
**ImportError: /usr/local/lib/python3.6/dist-packages/detectron2/_C.cpython-36m-aarch64-linux-gnu.so: undefined symbol: _ZN3c104cuda12device_countEv**

**Comment by neg-dev** [comment]
пересобрал модуль detectron2 с обновлёнными зависимостями
>pip3 install 'git+https://github.com/facebookresearch/detectron2.git'
ошибка решена

**Comment by ApelSYN** [comment]
Спасибо что поделились опытом решения проблемы, такая ошибка может появляться у других пользователей.
