### ISSUE TITLE
Video Memory Requirements

### ISSUE THREAD

**Issue by azhuchkov** [ria-com/nomeroff-net#122]
Running `python demo0.py` from `examples` folder on **GPU** (**GeForce GTX 1060 3GB**) produces the following results:
```
2021-02-11 12:14:25.171889: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
...
2021-02-11 12:12:05.446134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2545 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
Config '/home/common/nn/nomeroff-net/./NomeroffNet/configs/centermask2/numberplates/centermask_numberplate_V_39_eSE_FPN_ms_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "demo0.py", line 29, in <module>
    nnet.loadModel(NOMEROFF_NET_DIR)
  File "/home/common/nn/nomeroff-net/NomeroffNet/DetectronDetector.py", line 64, in loadModel
    self.predictor = DefaultPredictor(cfg)
  File "/home/common/nn/nomeroffnet.venv/lib64/python3.6/site-packages/detectron2/engine/defaults.py", line 216, in __init__
    self.model = build_model(self.cfg)
  File "/home/common/nn/nomeroffnet.venv/lib64/python3.6/site-packages/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model.to(torch.device(cfg.MODEL.DEVICE))
  File "/home/common/nn/nomeroffnet.venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/home/common/nn/nomeroffnet.venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/common/nn/nomeroffnet.venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/common/nn/nomeroffnet.venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/common/nn/nomeroffnet.venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: out of memory
```

There is no other processes that use this GPU during test: **nvidia-smi** shows that the python process starts consuming about 2700M from 0M and then the process fails.

So, how much of the memory does the tool require? I suppose it worth to mention hardware requirements somewhere in the docs as well.

**Comment by kurshakuz** [comment]
It takes up to ~1600 - ish Mb for me to run the demos. Try looking for more general solution for this error.

**Comment by ApelSYN** [comment]
> It takes up to ~1600 - ish Mb for me to run the demos. Try looking for more general solution for this error.

Thanks for your comment. Approximately 5G GPU is required for the module to work
