### ISSUE TITLE
Failed to run get-started-demo.py in docker container

### ISSUE THREAD

**Issue by Ridel89** [ria-com/nomeroff-net#258]
I builded docker image from build-cpu.sh and ran that image in bash mode. After that I tried to run get-started-demo.py and got the error: NotImplementedError: pretrained shufflenetv2_x2.0 is not supported as of now

Server: Docker Desktop 4.15.0 (93002)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  OS/Arch:          linux/amd64

Can you help me solve this issue?

[full-traceback.txt](https://github.com/ria-com/nomeroff-net/files/10489062/full-traceback.txt)

**Comment by ApelSYN** [comment]
Install a newer version of pyTorch, such as 1.13.1

**Comment by Ridel89** [comment]
Thanks a lot it helped!

**Comment by KVInventoR** [comment]
Hi @ApelSYN 
Looks like docker image required your attention:

```
root@3381703f0f31:/var/www/nomeroff-net/nomeroff-net# pip install pyTorch
Collecting pyTorch
  Downloading pytorch-1.0.2.tar.gz (689 bytes)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyTorch
  Building wheel for pyTorch (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-g8kska18/pytorch_0791a53d38074055becf58b8e3675e12/setup.py", line 15, in <module>
          raise Exception(message)
      Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyTorch
  Running setup.py clean for pyTorch
Failed to build pyTorch
Installing collected packages: pyTorch
  Running setup.py install for pyTorch ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pyTorch did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-g8kska18/pytorch_0791a53d38074055becf58b8e3675e12/setup.py", line 11, in <module>
          raise Exception(message)
      Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyTorch

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

```
