### ISSUE TITLE
Ошибка при установке пакета в req.txt

### ISSUE THREAD

**Issue by evgeniy1204** [ria-com/nomeroff-net#278]
Нужна помощь в подключении библотеки, подключаем пакет следующим образом в requirements.txt:
...
nomeroff_net @ git+https://github.com/ria-com/nomeroff-net.git@743a86245da157bff9296958acfa85645b377a0e

где 743a86245da157bff9296958acfa85645b377a0e последний коммит в мастер,
при билде докер контейнера появляется следующая ошибка:

`
        Building wheel for nomeroff_net (setup.py): started
        Building wheel for nomeroff_net (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
  
       × python setup.py bdist_wheel did not run successfully.
       │ exit code: 1
       ╰─> [290 lines of output]
           running bdist_wheel
           running build
          running build_py
          creating build
          creating build/lib
          creating build/lib/nomeroff_net
          copying nomeroff_net/__init__.py -> build/lib/nomeroff_net
          creating build/lib/nomeroff_net/pipelines

    ........

      copying build/lib/nomeroff_net/image_loaders/opencv_loader.py -> build/bdist.linux-x86_64/wheel/nomeroff_net/image_loaders
      copying build/lib/nomeroff_net/image_loaders/pillow_loader.py -> build/bdist.linux-x86_64/wheel/nomeroff_net/image_loaders
      copying build/lib/nomeroff_net/image_loaders/turbo_loader.py -> build/bdist.linux-x86_64/wheel/nomeroff_net/image_loaders
      warning: install_lib: byte-compiling is disabled, skipping.
      
      running install_egg_info
      Copying nomeroff_net.egg-info to build/bdist.linux-x86_64/wheel/nomeroff_net-3.4.1-py3.9.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/wheel/vendored/packaging/requirements.py", line 35, in __init__
          parsed = parse_requirement(requirement_string)
        File "/usr/local/lib/python3.9/site-packages/wheel/vendored/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "/usr/local/lib/python3.9/site-packages/wheel/vendored/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "/usr/local/lib/python3.9/site-packages/wheel/vendored/packaging/_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "/usr/local/lib/python3.9/site-packages/wheel/vendored/packaging/_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "/usr/local/lib/python3.9/site-packages/wheel/vendored/packaging/_tokenizer.py", line 163, in raise_syntax_error
          raise ParserSyntaxError(
      wheel.vendored.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
          imgaug>=0.4.*
                ~~~~~^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-wheel-5hlq3fyo/nomeroff-net_859b9704a95a4f8aa8e96bbc6e3ba96e/setup.py", line 31, in <module>
          setup(name='nomeroff-net',
        File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 401, in run
          self.egg2dist(self.egginfo_dir, distinfo_dir)
        File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 544, in egg2dist
          pkg_info = pkginfo_to_metadata(egginfo_path, pkginfo_path)
        File "/usr/local/lib/python3.9/site-packages/wheel/metadata.py", line 160, in pkginfo_to_metadata
          for key, value in generate_requirements({extra: reqs}):
        File "/usr/local/lib/python3.9/site-packages/wheel/metadata.py", line 138, in generate_requirements
          for new_req in convert_requirements(depends):
        File "/usr/local/lib/python3.9/site-packages/wheel/metadata.py", line 103, in convert_requirements
          parsed_requirement = Requirement(req)
        File "/usr/local/lib/python3.9/site-packages/wheel/vendored/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      wheel.vendored.packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
          imgaug>=0.4.*
                ~~~~~^
      [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for nomeroff_net
      Running setup.py clean for nomeroff_net
      Successfully built ninja2 PyTurboJPEG modelhub_client
      Failed to build nomeroff_net
`

однако если запустить python3 setup.py install - то все проходит без ошибок, как минимум с такой не падает, это как торешается? Заранее спасибо за ответ!

**Comment by plscrover** [comment]
Замените * на 0 в requirements.py
