### ISSUE TITLE
Error: Run on GPU

### ISSUE THREAD

**Issue by sashabal** [ria-com/nomeroff-net#32]
Hi Team

I have problem with run model on GPU. When I running script:
`import os
import cv2
import numpy as np
import sys
import json
import matplotlib.image as mpimg
import warnings
warnings.filterwarnings('ignore')

# change this property
NOMEROFF_NET_DIR = os.path.abspath('../../')

# specify the path to Mask_RCNN if you placed it outside Nomeroff-net project
MASK_RCNN_DIR = os.path.join(NOMEROFF_NET_DIR, 'Mask_RCNN')

MASK_RCNN_LOG_DIR = os.path.join(NOMEROFF_NET_DIR, 'logs')
MASK_RCNN_MODEL_PATH = os.path.join(NOMEROFF_NET_DIR, "models/mask_rcnn_numberplate_0700.h5")
OPTIONS_MODEL_PATH =  os.path.join(NOMEROFF_NET_DIR, "models/numberplate_options_2019_06_27.h5")

# If you use gpu version tensorflow please change model to gpu version named like *-gpu.pb
#mode =  "cpu" if  "NN_MODE" not in os.environ else os.environ["NN_MODE"] if os.environ["NN_MODE"]=="gpu" else "cpu"
mode = "gpu"
OCR_NP_UKR_TEXT =  os.path.join(NOMEROFF_NET_DIR, "models/anpr_ocr_ua_12-{}.h5".format(mode))
OCR_NP_EU_TEXT =  os.path.join(NOMEROFF_NET_DIR, "models/anpr_ocr_eu_2-{}.h5".format(mode))
OCR_NP_RU_TEXT =  os.path.join(NOMEROFF_NET_DIR, "models/anpr_ocr_ru_3-{}.h5".format(mode))

sys.path.append(NOMEROFF_NET_DIR)

# Import license plate recognition tools.
from NomeroffNet import  filters, RectDetector, TextDetector, OptionsDetector, Detector, textPostprocessing, textPostprocessing

# Initialize npdetector with default configuration file.
nnet = Detector(MASK_RCNN_DIR, MASK_RCNN_LOG_DIR)
nnet.loadModel(MASK_RCNN_MODEL_PATH)

rectDetector = RectDetector()

optionsDetector = OptionsDetector()
optionsDetector.load(OPTIONS_MODEL_PATH)

# Initialize text detector.
textDetector = TextDetector({
    "eu_ua_2004_2015": {
        "for_regions": ["eu_ua_2015", "eu_ua_2004"],
        "model_path": OCR_NP_UKR_TEXT
    },
    "eu": {
        "for_regions": ["eu", "eu_ua_1995"],
        "model_path": OCR_NP_EU_TEXT
    },
    "ru": {
        "for_regions": ["ru"],
        "model_path": OCR_NP_RU_TEXT
    }
})

# Walking through the ./examples/images/ directory and checking each of the images for license plates.
rootDir = '../../images/'

max_img_w = 1600
for dirName, subdirList, fileList in os.walk(rootDir):
    for fname in fileList:
        img_path = os.path.join(dirName, fname)
        print(img_path)
        img = mpimg.imread(img_path)

        # corect size for better speed
        img_w = img.shape[1]
        img_h = img.shape[0]
        img_w_r = 1
        img_h_r = 1
        if img_w > max_img_w:
            resized_img = cv2.resize(img, (max_img_w, int(max_img_w/img_w*img_h)))
            img_w_r = img_w/max_img_w
            img_h_r = img_h/(max_img_w/img_w*img_h)
        else:
            resized_img = img

        NP = nnet.detect([resized_img])

        # Generate image mask.
        cv_img_masks = filters.cv_img_mask(NP)

        # Detect points.
        arrPoints = rectDetector.detect(cv_img_masks, outboundHeightOffset=3-img_w_r)
#       print(arrPoints)
        arrPoints[..., 1:2] = arrPoints[..., 1:2]*img_h_r
        arrPoints[..., 0:1] = arrPoints[..., 0:1]*img_w_r

        # cut zones
        zones = rectDetector.get_cv_zonesBGR(img, arrPoints)

        # find standart
        regionIds, stateIds, countLines = optionsDetector.predict(zones)
        regionNames = optionsDetector.getRegionLabels(regionIds)
        print(regionNames)

        # find text with postprocessing by standart
        textArr = textDetector.predict(zones, regionNames)
        textArr = textPostprocessing(textArr, regionNames)
        print(textArr)`

 **with mode = "gpu", I am get error:**

`Traceback (most recent call last):
  File "test.py", line 54, in <module>
    "model_path": OCR_NP_RU_TEXT
  File "/home/ubuntu/nomeroff-net/NomeroffNet/TextDetector.py", line 37, in __init__
    detector.load(priset['model_path'])
  File "/home/ubuntu/nomeroff-net/NomeroffNet/Base/OCR.py", line 190, in load
    self.MODEL = load_model(path_to_model, compile=False)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 287, in _deserialize_model
    K.batch_set_value(weight_value_tuples)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2470, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 199, in get_session
    [tf.is_variable_initialized(v) for v in candidate_vars])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by node gru1/CudnnRNN (defined at /home/ubuntu/.local/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:297) with these attrs: [T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="gru", is_training=true, seed2=0, dropout=0, seed=87654321]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[gru1/CudnnRNN]]

Errors may have originated from an input operation.
Input Source operations connected to node gru1/CudnnRNN:
 gru1/ExpandDims_1 (defined at /home/ubuntu/.local/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:273)	
 gru1/concat (defined at /home/ubuntu/.local/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:60)	
 gru1/transpose (defined at /home/ubuntu/.local/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:271)`

Help me please, for solve this problem...

**Comment by dimabendera** [comment]
Hi, 
Pay attention to
> Registered devices: [CPU, XLA_CPU]

you have to use tensorflow-gpu to work on  your GPU device.

Please run this code to make sure
https://github.com/ria-com/nomeroff-net/issues/29#issuecomment-512229409

**Comment by sashabal** [comment]
I am get:

/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING: Logging before flag parsing goes to stderr.
W0729 12:36:46.215900 140500138620736 deprecation_wrapper.py:119] From 1.py:2: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0729 12:36:46.216178 140500138620736 deprecation_wrapper.py:119] From 1.py:2: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-07-29 12:36:46.232007: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-29 12:36:46.237208: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2095145000 Hz
2019-07-29 12:36:46.238391: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x17fb770 executing computations on platform Host. Devices:
2019-07-29 12:36:46.238431: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
2019-07-29 12:36:46.239695: I tensorflow/core/common_runtime/direct_session.cc:296] Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device

MatMul: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0
2019-07-29 12:36:46.243862: I tensorflow/core/common_runtime/placer.cc:54] MatMul: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0
a: (Const): /job:localhost/replica:0/task:0/device:CPU:0
2019-07-29 12:36:46.243895: I tensorflow/core/common_runtime/placer.cc:54] a: (Const)/job:localhost/replica:0/task:0/device:CPU:0
b: (Const): /job:localhost/replica:0/task:0/device:CPU:0
2019-07-29 12:36:46.243914: I tensorflow/core/common_runtime/placer.cc:54] b: (Const)/job:localhost/replica:0/task:0/device:CPU:0
2019-07-29 12:36:46.244432: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
[[22. 28.]
 [49. 64.]]

**Comment by dimabendera** [comment]
Yes, you use CPU version tensorflow.

If your device support GPU follow this guide
https://www.tensorflow.org/install/gpu

**Comment by sashabal** [comment]
Thank's. I was able to run on GPU.
I have 16 VRAM. I want to run in three threads. But when I run one thread, it uses all the memory.
How can I limit the amount of VRAM per thread?

**Comment by sashabal** [comment]
I get a out of memory when I run the second thread:

2019-07-29 15:14:46.026772: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0x7f5a8a927d00 next 439 of size 1024
2019-07-29 15:14:46.026781: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0x7f5a8a928100 next 440 of size 1024
2019-07-29 15:14:46.026790: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0x7f5a8a928500 next 441 of size 1024
2019-07-29 15:14:46.026800: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0x7f5a8a928900 next 442 of size 4096
2019-07-29 15:14:46.026809: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0x7f5a8a929900 next 443 of size 4096
2019-07-29 15:14:46.026819: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0x7f5a8a92a900 next 444 of size 589824
2019-07-29 15:14:46.026829: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0x7f5a8a9ba900 next 445 of size 589824
2019-07-29 15:14:46.026838: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0x7f5a8aa4a900 next 446 of size 589824
2019-07-29 15:14:46.026849: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0x7f5a8aada900 next 18446744073709551615 of size 1070848
2019-07-29 15:14:46.026860: I tensorflow/core/common_runtime/bfc_allocator.cc:809]      Summary of in-use Chunks by size: 
2019-07-29 15:14:46.026873: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 83 Chunks of size 256 totalling 20.8KiB
2019-07-29 15:14:46.026886: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 39 Chunks of size 512 totalling 19.5KiB
2019-07-29 15:14:46.026897: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 136 Chunks of size 1024 totalling 136.0KiB
2019-07-29 15:14:46.026907: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 1280 totalling 1.2KiB
2019-07-29 15:14:46.026918: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 52 Chunks of size 2048 totalling 104.0KiB
2019-07-29 15:14:46.026929: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 68 Chunks of size 4096 totalling 272.0KiB
2019-07-29 15:14:46.026940: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 21 Chunks of size 8192 totalling 168.0KiB
2019-07-29 15:14:46.026951: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 12288 totalling 12.0KiB
2019-07-29 15:14:46.026962: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 16384 totalling 16.0KiB
2019-07-29 15:14:46.026973: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 24576 totalling 24.0KiB
2019-07-29 15:14:46.026983: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 37632 totalling 36.8KiB
2019-07-29 15:14:46.026995: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 2 Chunks of size 65536 totalling 128.0KiB
2019-07-29 15:14:46.027005: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 7 Chunks of size 262144 totalling 1.75MiB
2019-07-29 15:14:46.027016: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 3 Chunks of size 524288 totalling 1.50MiB
2019-07-29 15:14:46.027029: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 3 Chunks of size 589824 totalling 1.69MiB
2019-07-29 15:14:46.027041: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 23 Chunks of size 1048576 totalling 23.00MiB
2019-07-29 15:14:46.027055: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 1070848 totalling 1.02MiB
2019-07-29 15:14:46.027066: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 2097152 totalling 2.00MiB
2019-07-29 15:14:46.027077: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 3 Chunks of size 4194304 totalling 12.00MiB
2019-07-29 15:14:46.027087: I tensorflow/core/common_runtime/bfc_allocator.cc:816] Sum Total of in-use chunks: 43.88MiB
2019-07-29 15:14:46.027102: I tensorflow/core/common_runtime/bfc_allocator.cc:818] total_region_allocated_bytes_: 46006272 memory_limit_: 46006272 available bytes: 0 curr_region_allocation_bytes_: 92012544
2019-07-29 15:14:46.027116: I tensorflow/core/common_runtime/bfc_allocator.cc:824] Stats: 
Limit:                    46006272
InUse:                    46006272
MaxInUse:                 46006272
NumAllocs:                     447
MaxAllocSize:              4194304

2019-07-29 15:14:46.027167: W tensorflow/core/common_runtime/bfc_allocator.cc:319] ***************************************************************************************************x
2019-07-29 15:14:46.027209: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at assign_op.h:117 : Resource exhausted: OOM when allocating tensor with shape[1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

**Comment by dimabendera** [comment]
use this code:
```python
import keras
import tensorflow as tf


config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = (1 / 3)
config.gpu_options.allow_growth = True
keras.backend.set_session(tf.Session(config=config))
```
where 3 it ts your count of threads

**Comment by sashabal** [comment]
Thank's it is working!
