### ISSUE TITLE
Ошибка оучения mrcnn

### ISSUE THREAD

**Issue by flash1nho** [ria-com/nomeroff-net#57]
Использовал этот dataset: https://nomeroff.net.ua/datasets/autoriaNumberplateDataset-2019-03-06.zip

Упала ошибка:
```
Traceback (most recent call last):
  File "m.py", line 41, in <module>
    nnet.train()
  File "/nomeroff-net/NomeroffNet/Detector.py", line 243, in train
    layers=self.CONFIG.LAYERS )
  File "/usr/local/lib/python3.6/site-packages/mrcnn/model.py", line 2374, in train
    use_multiprocessing=True,
  File "/usr/local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 733, in get
    six.reraise(*sys.exc_info())
  File "/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 702, in get
    inputs = future.get(timeout=30)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
IndexError: index 1159 is out of bounds for axis 1 with size 1080
```

**Comment by ApelSYN** [comment]
Ответил как фиксить в этой ветке https://github.com/ria-com/nomeroff-net/issues/56#issuecomment-559037078

**Comment by flash1nho** [comment]
Спасибо! Вроде заработало.
