### ISSUE TITLE
module 'numpy.random' has no attribute 'bit_generator'

### ISSUE THREAD

**Issue by caesarisme** [ria-com/nomeroff-net#63]
При импорте модулей возникает ошибка

Traceback (most recent call last):
  File "demo0.py", line 17, in <module>
    from NomeroffNet import  filters, RectDetector, TextDetector, OptionsDetector, Detector, textPostprocessing, textPostprocessingAsync
  File "/Users/caesarisme/Desktop/clr3/nomeroff-net/examples/py/../../NomeroffNet/__init__.py", line 5, in <module>
    from .TextDetector import *
  File "/Users/caesarisme/Desktop/clr3/nomeroff-net/examples/py/../../NomeroffNet/TextDetector.py", line 4, in <module>
    import TextDetectors
  File "/Users/caesarisme/Desktop/clr3/nomeroff-net/NomeroffNet/TextDetectors/__init__.py", line 6, in <module>
    importlib.import_module(modname)
  File "/Users/caesarisme/Desktop/clr3/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/caesarisme/Desktop/clr3/nomeroff-net/NomeroffNet/TextDetectors/eu.py", line 1, in <module>
    from Base import OCR
  File "/Users/caesarisme/Desktop/clr3/nomeroff-net/NomeroffNet/Base/__init__.py", line 1, in <module>
    from .OCR import *
  File "/Users/caesarisme/Desktop/clr3/nomeroff-net/NomeroffNet/Base/OCR.py", line 26, in <module>
    from .TextImageGenerator import TextImageGenerator
  File "/Users/caesarisme/Desktop/clr3/nomeroff-net/NomeroffNet/Base/TextImageGenerator.py", line 9, in <module>
    from .aug import aug
  File "/Users/caesarisme/Desktop/clr3/nomeroff-net/NomeroffNet/Base/aug.py", line 5, in <module>
    ia.seed(1)
  File "/Users/caesarisme/Desktop/clr3/venv/lib/python3.7/site-packages/imgaug/imgaug.py", line 502, in seed
    imgaug.random.seed(entropy)
  File "/Users/caesarisme/Desktop/clr3/venv/lib/python3.7/site-packages/imgaug/random.py", line 762, in seed
    _seed_np117_(entropy)
  File "/Users/caesarisme/Desktop/clr3/venv/lib/python3.7/site-packages/imgaug/random.py", line 770, in _seed_np117_
    GLOBAL_RNG = RNG(entropy)
  File "/Users/caesarisme/Desktop/clr3/venv/lib/python3.7/site-packages/imgaug/random.py", line 142, in __init__
    self.generator = normalize_generator_(generator)
  File "/Users/caesarisme/Desktop/clr3/venv/lib/python3.7/site-packages/imgaug/random.py", line 841, in normalize_generator_
    return _normalize_generator_np117_(generator)
  File "/Users/caesarisme/Desktop/clr3/venv/lib/python3.7/site-packages/imgaug/random.py", line 851, in _normalize_generator_np117_
    elif isinstance(generator, np.random.bit_generator.BitGenerator):
AttributeError: module 'numpy.random' has no attribute 'bit_generator'

**Comment by ApelSYN** [comment]
Чттб получить ответ на такого рода вопросы указывайте техническую информацию о вашей системе:
версия OS, версия python, возможно характеристики железа (на котором запускаете), если возникла ошибка при работе с модулем numpy, то версию numpy

**Comment by nani-ka** [comment]
Это из-за последней версии numpy 1.18, установите версию 1.17

**Comment by caesarisme** [comment]
> Чттб получить ответ на такого рода вопросы указывайте техническую информацию о вашей системе:
> версия OS, версия python, возможно характеристики железа (на котором запускаете), если возникла ошибка при работе с модулем numpy, то версию numpy

Извиняюсь, не имею большого опыта с ML

MacOS Catalina 10.15.1
Python 3.7.5
numpy 1.18.0

**Comment by caesarisme** [comment]
> Это из-за последней версии numpy 1.18, установите версию 1.17

Спасибо, решило проблему
