### ISSUE TITLE
OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by marker91** [ria-com/nomeroff-net#72]
Доброго времени суток, возникла ошибка при попытке запустить demo:

`Traceback (most recent call last):
  File "recognition.py", line 33, in <module>
    textDetector.load("/srv/nomeroff-net/models/anpr_ocr_eu_2-cpu.pb")
  File "/usr/local/lib/python3.6/dist-packages/NomeroffNet/Base/OCR.py", line 190, in load
    self.MODEL = load_model(path_to_model, compile=False)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 549, in load_model
    with H5Dict(filepath, mode='r') as h5dict:
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)`

пробовал различные файлы по указанной в документации ссылке [https://nomeroff.net.ua/models/ocr/](https://nomeroff.net.ua/models/ocr/) и каждый выдаёт такую ошибку, подскажите пожалуйста, в чем может быть проблема?

**Comment by marker91** [comment]
надо использовать *.h5 файлы
