### ISSUE TITLE
Ошибка при распознавании в demo

### ISSUE THREAD

**Issue by marker91** [ria-com/nomeroff-net#73]
Доброго времени суток, при распознавании чёрно-белого изображения в demo0 происходит ошибка:
`Traceback (most recent call last):
  File "c:/Users/zakha/OneDrive/Рабочий стол/recognition.py", line 35, in <module>
    NP = nnet.detect([img])
  File "C:\Users\zakha\AppData\Local\Programs\Python\Python37\lib\site-packages\NomeroffNet\Detector.py", line 98, in detect
    return self.MODEL.detect(self.normalize(images), verbose=verbose)
  File "C:\Users\zakha\AppData\Local\Programs\Python\Python37\lib\site-packages\mrcnn\model.py", line 2503, in detect
    molded_images, image_metas, windows = self.mold_inputs(images)
  File "C:\Users\zakha\AppData\Local\Programs\Python\Python37\lib\site-packages\mrcnn\model.py", line 2401, in mold_inputs
    mode=self.config.IMAGE_RESIZE_MODE)
  File "C:\Users\zakha\AppData\Local\Programs\Python\Python37\lib\site-packages\mrcnn\utils.py", line 459, in resize_image
    image = np.pad(image, padding, mode='constant', constant_values=0)
  File "<__array_function__ internals>", line 6, in pad
  File "C:\Users\zakha\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\arraypad.py", line 748, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
  File "C:\Users\zakha\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\arraypad.py", line 523, in _as_pairs
    return np.broadcast_to(x, (ndim, 2)).tolist()
  File "<__array_function__ internals>", line 6, in broadcast_to
  File "C:\Users\zakha\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "C:\Users\zakha\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\stride_tricks.py", line 127, in _broadcast_to
    op_flags=['readonly'], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,2) and requested shape (2,2)`

попробовал распознать через https://nomeroff.net.ua/onlinedemo.html, там всё распознается корректно с тем же изображением, подскажите пожалуйста куда копать?

**Comment by dimabendera** [comment]
Попробуйте сделать

```python3
print(img.shape)
```

Возможно изображение прочиталось не в том формате
Конвертировать вы можете с помощью cv2 например
```python3
image = cv2.cvtColor(src, cv2.COLOR_RGBA2RGB ) 
```

**Comment by marker91** [comment]
@dimabendera, спасибо
